#!/bin/bash
#
# Usage:
#
#   N=nnn; random.awk $N | [dir=Debug] ./$0 [-N $N] [-Z 999] ...
#
${dir:=Release}/Sort -UfdK3wjhSarqkm \
    -t -P 31,63,127,255,1023,4095 \
    -I qm -B 8191 \
    -R 1 \
    $*	# You can add parameters
