#!/bin/bash
#
# Usage:
#
#   N=nnn; random.awk $N | [dir=Debug] ./$0 [-N $N] ...
#
#     ex) N=234567; random.awk $N | ./$0 -N $N -Z 1000
#
${dir:=Release}/Sort -fdK3wjhSartqkm -I qm \
    -P 31,63,127,255,1023,4095 \
    -B 8191 \
    -R 1 \
    $*	# You can overwrite and add parameters such as "-U".
